spring:
  flyway:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_DATABASE_URL:localhost}:5432/${POSTGRES_DB:persons}
    username: ${POSTGRES_USER:persons}
    password: ${POSTGRES_PASSWORD:persons}
